export enum UserRoleEnum {
  ADMIN = "ADMIN",
  BUSINESS = "BUSINESS",
  USER = "USER",
}
export enum BusinessTypeEnum {
  COMPANY = "COMPANY",
  INDIVIDUAL = "INDIVIDUAL",
}
export enum CarStatusEnum {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  RENTED = "RENTED",
  REJECTED = "REJECTED",
  HIDDEN = "HIDDEN",
}
export enum CarTypeEnum {
  SUV = "SUV",
  SEDAN = "SEDAN",
  HATCHBACK = "HATCHBACK",
  PICKUP = "PICKUP",
  MPV = "MPV",
  COUPE = "COUPE",
  CONVERTIBLE = "CONVERTIBLE",
  ELECTRIC = "ELECTRIC",
}

export enum FuelTypeEnum {
  GASOLINE = "GASOLINE",
  DIESEL = "DIESEL",
  ELECTRIC = "ELECTRIC",
  HYBRID = "HYBRID",
}

export enum TransmissionEnum {
  AUTOMATIC = "AUTOMATIC",
  MANUAL = "MANUAL",
}
export enum CartStatusEnum {
  ACTIVE = "ACTIVE",
  EXPIRED = "EXPIRED",
  BOOKED = "BOOKED",
  CANCELLED = "CANCELLED",
}

export enum BookingStatusEnum {
  REQUESTED = "REQUESTED", // Khách đã gửi yêu cầu thuê, đang chờ chủ xe duyệt
  OWNER_APPROVED = "OWNER_APPROVED", // Chủ xe đã đồng ý cho thuê, khách có thể tạo hợp đồng/thanh toán
  PAYMENT_PENDING = "PAYMENT_PENDING", // Khách đã bắt đầu thanh toán, hệ thống đang chờ kết quả/ghi nhận
  PAID = "PAID", // Khách đã thanh toán đủ khoản cần trả trước, lịch thuê được giữ chính thức
  IN_PROGRESS = "IN_PROGRESS", // Chủ xe đã bàn giao xe, chuyến thuê đang diễn ra
  RETURN_INSPECTION = "RETURN_INSPECTION",
  AWAITING_EXTRA_CHARGE = "AWAITING_EXTRA_CHARGE",
  COMPLETED = "COMPLETED", // Chuyến thuê đã hoàn tất
  CANCELLED = "CANCELLED", // Khách hoặc hệ thống đã hủy booking
  REJECTED = "REJECTED", // Chủ xe từ chối yêu cầu thuê
  NO_SHOW = "NO_SHOW", // Khách không đến nhận xe đúng lịch
  PENDING = "PENDING", // Trạng thái cũ: tương đương REQUESTED, giữ lại để đọc dữ liệu cũ
  WAITING_PAYMENT = "WAITING_PAYMENT", // Trạng thái cũ: tương đương PAYMENT_PENDING, giữ lại để đọc dữ liệu cũ
  CONFIRMED = "CONFIRMED", // Trạng thái cũ: tương đương OWNER_APPROVED/PAID tùy ngữ cảnh, giữ lại để đọc dữ liệu cũ
}

export enum PaymentStatusEnum {
  PENDING = "PENDING",
  PAID = "PAID",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}

export enum PaymentMethodEnum {
  CASH = "CASH",
  MOMO = "MOMO",
  VNPAY = "VNPAY",
}
export enum PaymentOptionEnum {
  DEPOSIT = "DEPOSIT",
  FULL = "FULL",
}

export enum PaymentTypeEnum {
  DEPOSIT = "DEPOSIT",
  FULL = "FULL",
  REMAINING = "REMAINING",
  EXTRA_CHARGE = "EXTRA_CHARGE",
}
export enum RefundStatusEnum {
  PENDING = "PENDING",
  WAITING_FOR_REFUND_INFO = "WAITING_FOR_REFUND_INFO",
  PROCESSING = "PROCESSING",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
  MANUAL_REQUIRED = "MANUAL_REQUIRED",
  CANCELLED = "CANCELLED",
}
export enum RefundMethodEnum {
  VNPAY = "VNPAY",
  MOMO = "MOMO",
  CASH = "CASH",
  MANUAL = "MANUAL",
  NONE = "NONE",
}
export enum DeliveryTypeEnum {
  PICKUP_AT_CAR_LOCATION = "PICKUP_AT_CAR_LOCATION",
  DELIVERY_TO_CUSTOMER = "DELIVERY_TO_CUSTOMER",
}
export enum DeliveryAddressSourceEnum {
  MANUAL_TEXT = "MANUAL_TEXT",
  GEOCODE = "GEOCODE",
  CURRENT_LOCATION = "CURRENT_LOCATION",
  MAP_PIN = "MAP_PIN",
}
export enum ExtraChargeTypeEnum {
  CLEANING = "CLEANING",
  DAMAGE = "DAMAGE",
  LATE_RETURN = "LATE_RETURN",
  FUEL = "FUEL",
  OTHER = "OTHER",
}
export enum ExtraChargeStatusEnum {
  PENDING = "PENDING",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
}
export enum ReturnInspectionStatusEnum {
  RECEIVED = "RECEIVED",
  INSPECTING = "INSPECTING",
  CHARGES_PENDING = "CHARGES_PENDING",
  CLEARED = "CLEARED",
}
export enum RentalUnitEnum {
  DAY = "DAY",
  HOUR = "HOUR",
}
export enum RentalModeEnum {
  DAILY = "DAILY",
  HOURLY = "HOURLY",
}
export enum PricingDateTypeEnum {
  WEEKDAY = "WEEKDAY",
  WEEKEND = "WEEKEND",
  HOLIDAY = "HOLIDAY",
}
export enum ContractStatusEnum {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}
export enum OwnerTypeEnum {
  BUSINESS = "BUSINESS",
  USER = "USER",
}

export enum NotificationEntityTypeEnum {
  BOOKING = "BOOKING",
  PAYMENT = "PAYMENT",
  REFUND = "REFUND",
  CAR = "CAR",
  CONTRACT = "CONTRACT",
  EXTRA_CHARGE = "EXTRA_CHARGE",
  REVIEW = "REVIEW",
  RETURN_INSPECTION = "RETURN_INSPECTION",
  BUSINESS = "BUSINESS",
  USER = "USER",
  SYSTEM = "SYSTEM",
}

export enum NotificationTypeEnum {
  BOOKING_CREATED = "BOOKING_CREATED",
  BOOKING_APPROVED = "BOOKING_APPROVED",
  BOOKING_REJECTED = "BOOKING_REJECTED",
  BOOKING_CANCELLED = "BOOKING_CANCELLED",
  BOOKING_NO_SHOW = "BOOKING_NO_SHOW",
  BOOKING_COMPLETED = "BOOKING_COMPLETED",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  DEPOSIT_PAID = "DEPOSIT_PAID",
  FULL_PAYMENT_PAID = "FULL_PAYMENT_PAID",
  REMAINING_PAYMENT_PAID = "REMAINING_PAYMENT_PAID",
  CASH_PAYMENT_CONFIRMED = "CASH_PAYMENT_CONFIRMED",
  PAYMENT_REFUNDED = "PAYMENT_REFUNDED",
  REFUND_RECIPIENT_INFO_SUBMITTED = "REFUND_RECIPIENT_INFO_SUBMITTED",
  HANDOVER_COMPLETED = "HANDOVER_COMPLETED",
  RETURN_RECEIVED = "RETURN_RECEIVED",
  RETURN_INSPECTION_CLEARED = "RETURN_INSPECTION_CLEARED",
  EXTRA_CHARGE_CREATED = "EXTRA_CHARGE_CREATED",
  EXTRA_CHARGE_PAID = "EXTRA_CHARGE_PAID",
  EXTRA_CHARGE_CANCELLED = "EXTRA_CHARGE_CANCELLED",
  REVIEW_CREATED = "REVIEW_CREATED",
  REVIEW_OWNER_REPLIED = "REVIEW_OWNER_REPLIED",
  REVIEW_HIDDEN = "REVIEW_HIDDEN",
  REVIEW_RESTORED = "REVIEW_RESTORED",
  CAR_SUBMITTED = "CAR_SUBMITTED",
  CAR_APPROVED = "CAR_APPROVED",
  CAR_REJECTED = "CAR_REJECTED",
  CAR_HIDDEN = "CAR_HIDDEN",
  BUSINESS_APPROVED = "BUSINESS_APPROVED",
  BUSINESS_REJECTED = "BUSINESS_REJECTED",
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
  ACCOUNT_UNLOCKED = "ACCOUNT_UNLOCKED",
  CONTRACT_CREATED = "CONTRACT_CREATED",
  CONTRACT_UPDATED = "CONTRACT_UPDATED",
  SYSTEM = "SYSTEM",
}

export enum NotificationActionKeyEnum {
  VIEW_BOOKING = "VIEW_BOOKING",
  PAY_REMAINING = "PAY_REMAINING",
  VIEW_CAR = "VIEW_CAR",
  VIEW_EXTRA_CHARGE = "VIEW_EXTRA_CHARGE",
  LEAVE_REVIEW = "LEAVE_REVIEW",
  VIEW_REVIEW = "VIEW_REVIEW",
  VIEW_CONTRACT = "VIEW_CONTRACT",
  VIEW_PROFILE = "VIEW_PROFILE",
}
